# XIAOMA™ Method Core Configuration

code: xmb
name: "XMB: XiaoMa Builder - Agent, Workflow and Module Builder"
default_selected: false # This module will not be selected by default for new installations

header: "XiaoMa Optimized Builder (BoMB) Module Configuration"
subheader: "Configure the settings for the BoMB Factory!\nThe agent, workflow and module builder for XIAOMA™"

# Variables from Core Config inserted:
## user_name
## communication_language
## output_folder
## xiaoma_folder
## install_user_docs
## kb_install

custom_agent_location:
  default: ".xiaoma/custom/src/agents"
  result: "{project-root}/{value}"

custom_workflow_location:
  default: ".xiaoma/custom/src/workflows"
  result: "{project-root}/{value}"

custom_module_location:
  default: ".xiaoma/custom/src/modules"
  result: "{project-root}/{value}"
